
name: Movies CI/CD Pipeline
run-name: Krufe
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Installing Npm
      run: npm install
    - name: Testing
      run: npm run test:unit
    - name: Displaying my username
      run: echo "Krufeee"
      
  deploy:
        needs: build
        runs-on: ubuntu-latest
        
        steps:
        - name: Render Deploy Action
          uses: johnbeynon/render-deploy-action@v0.0.8
          with:
            service-id: ${{ secrets.WEB_HOOK }}
            api-key: ${{ secrets.WEB_SERVICE }}
    
  Testing:
        needs: deploy
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        - name: Use Node.js 14.x
          uses: actions/setup-node@v3
          with:
            node-version: 14.x
            cache: 'npm'
        - name: Installing Npm
          run: npm install
        - name: Install Playwright Browser
          run: npx playwright install --with-deps
        - name: Testing
          run: npm run test:ui